{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ printf "%s-gateway" (include "clearnode.common.fullname" .) }}
  labels:
    {{- include "clearnode.common.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.gateway.tlsClusterIssuer }}
    {{- if .Values.gateway.ipAddress }}
    gateway.envoyproxy.io/service-annotations: |
      networking.gke.io/load-balancer-ip-addresses: "{{ .Values.gateway.ipAddressName }}"
    {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: http
      protocol: HTTP
      hostname: {{ .Values.gateway.externalHostname }}
      port: 80
    - name: https
      protocol: HTTPS
      hostname: {{ .Values.gateway.externalHostname }}
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ printf "%s-tls" (.Values.gateway.externalHostname | replace "." "-") }}
{{- end }}
