name: Push on main branch

on:
  push:
    branches:
      - main

jobs:
  auto-tag-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run auto tag script
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          
          ./scripts/auto_tag.sh
      
      - name: Get the new tag
        id: tagger
        run: |
          NEW_TAG=$(git describe --tags --abbrev=0)
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.tagger.outputs.new_tag }}
            ghcr.io/${{ github.repository }}:latest-rc
          cache-from: type=gha
          cache-to: type=gha,mode=max
